steps:
- name: gcr.io/cloud-builders/gcloud
  id: "Build docker image"
  args: ['builds', 'submit', '--tag', '$_TEMPLATE_IMAGE', '.']
  waitFor: ['-']
- name: gcr.io/cloud-builders/gcloud
  args: ['dataflow', 
         'flex-template',
         'build',
         'gs://$_GCP_BUCKET/dataflow-templates/dataflow-twitter.json',
         '--image=$_TEMPLATE_IMAGE',
         '--sdk-language=PYTHON'
  ] 
  waitFor: ['Build docker image']
